### ISSUE TITLE
Curious what this does differently vs. something like k9s?

### ISSUE THREAD

**Issue by slmingol** [pymag09/kubecui#1]
- https://k9scli.io/topics/commands/
- https://computingforgeeks.com/k9s-kubernetes-cli-to-manage-clusters-in-style/

Show similar features from what I can tell to what you're building here. Just curious.

**Comment by pymag09** [comment]
@slmingol 

https://www.reddit.com/r/kubernetes/comments/vt5ers/comment/if6bjdq/?utm_source=share&utm_medium=web2x&context=3

**Comment by pymag09** [comment]
And pay special attention to `k explain` command.
>  **Probably none of the tools like Lens or k9s can do what “kubectl explain” does, but interactive “explain” is even better.**
https://medium.com/@magelan09/kubectl-on-steroids-there-is-life-beyond-k9s-5c214e878c83
