### ISSUE TITLE
[F1]Explain results in error due to known option for yq/jq

### ISSUE THREAD

**Issue by drshawnkwang** [pymag09/kubecui#4]
Steps to reproduce:

1. `k get pods`
1. select a pod and press F1

Visible error message:
```
jq: Unknown option -o
                     Use jq --help for help with command-line options,
                                                                      or see the jq manpage, or online docs  at https://jqlang.github.io/jq
```

I also believe I see a "Broken pipe" error but it does not persist on screen.

My install of `jq` and `yq` on a Debian linux system are versions: 

```
jq 1.7.1-3
yq 3.2.3.-1
```

Neither has option `-o` available.

I thought `fx/libs/explain.sh`, line 4 may be the culprit

```
EXPLAIN=$(kubectl explain ${RS_TYPE} --recursive | sed -r 's/FIELDS:/---/' | sed -n '\|---|,$p' | sed -r 's/(\w+)\t.*/\1:/g' | yq -o props -P . | sed -r 's/ =//g')
```

I tried removing the `-o` and `-P` options, so the line reads as follows:

```
EXPLAIN=$(kubectl explain ${RS_TYPE} --recursive | sed -r 's/FIELDS:/---/' | sed -n '\|---|,$p' | sed -r 's/(\w+)\t.*/\1:/g' | yq . | sed -r 's/ =//g')
```

Update: I forgot to source the `kubecui.sh` file after my change. After changing the `EXPLAIN` line 4, and removing the `-o` and `-P`, the F1 button for Explain "works". Although the results may not have been what you originally intended. Without knowing what these two options were suppose to do, I can't really figure out what the change in behavior is.

Let me know if there is anything else I can test to help determine the root cause of the issue.

**Comment by pymag09** [comment]
My version of `yq` is:
```
yq --version
yq (https://github.com/mikefarah/yq/) version v4.40.5
```
These options are:
```
-o, --output-format string          [auto|a|yaml|y|json|j|props|p|xml|x|tsv|t|csv|c] output format type. (default "auto")
-P, --prettyPrint                   pretty print, shorthand for '... style = ""'
```
The latest version of `yq` has all these flags. https://github.com/mikefarah/yq#usage
Try to upgrade `yq`

**Comment by drshawnkwang** [comment]
That makes sense. I am using Debian/testing's package for `yq`, hence v3.2.3-1. Thanks for the fast response, I'll look into updating.
